const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  startStream: (requestId, messages, options) => ipcRenderer.send('start-stream', requestId, messages, options),
  stopStream: (requestId) => ipcRenderer.send('stop-stream', requestId),
  onChunk: (cb) => { ipcRenderer.removeAllListeners('stream-chunk'); ipcRenderer.on('stream-chunk', (_, requestId, data) => cb(requestId, data)); },
  onThinking: (cb) => { ipcRenderer.removeAllListeners('stream-thinking'); ipcRenderer.on('stream-thinking', (_, requestId, data) => cb(requestId, data)); },
  onDone: (cb) => { ipcRenderer.removeAllListeners('stream-done'); ipcRenderer.on('stream-done', (_, requestId) => cb(requestId)); },
  onError: (cb) => { ipcRenderer.removeAllListeners('stream-error'); ipcRenderer.on('stream-error', (_, requestId, error, details) => cb(requestId, error, details)); },
  onUsage: (cb) => { ipcRenderer.removeAllListeners('stream-usage'); ipcRenderer.on('stream-usage', (_, requestId, usage) => cb(requestId, usage)); },
  onTool: (cb) => { ipcRenderer.removeAllListeners('stream-tool'); ipcRenderer.on('stream-tool', (_, requestId, tool) => cb(requestId, tool)); },
  onArtifacts: (cb) => { ipcRenderer.removeAllListeners('stream-artifacts'); ipcRenderer.on('stream-artifacts', (_, requestId, artifacts) => cb(requestId, artifacts)); },
  onNewQuery: (cb) => ipcRenderer.on('new-query', (_, text) => cb(text)),
  onSelectionDraft: (cb) => ipcRenderer.on('selection-draft', (_, text) => cb(text)),
  onBilibiliAuthChanged: (cb) => { ipcRenderer.removeAllListeners('bilibili-auth-changed'); ipcRenderer.on('bilibili-auth-changed', (_, state) => cb(state)); },
  onFullscreenChanged: (cb) => { ipcRenderer.removeAllListeners('fullscreen-changed'); ipcRenderer.on('fullscreen-changed', (_, state) => cb(state)); },
  onAppMenuAction: (cb) => { ipcRenderer.removeAllListeners('app-menu-action'); ipcRenderer.on('app-menu-action', (_, action) => cb(action)); },
  onAlwaysOnTopChanged: (cb) => { ipcRenderer.removeAllListeners('always-on-top-changed'); ipcRenderer.on('always-on-top-changed', (_, state) => cb(state)); },
  onDisplayProfileChanged: (cb) => { ipcRenderer.removeAllListeners('display-profile-changed'); ipcRenderer.on('display-profile-changed', (_, profile) => cb(profile)); },
  onLearningUpdated: (cb) => { ipcRenderer.removeAllListeners('learning-updated'); ipcRenderer.on('learning-updated', (_, dashboard) => cb(dashboard)); },
  onLearningConversationsUpdated: (cb) => { ipcRenderer.removeAllListeners('learning-conversations-updated'); ipcRenderer.on('learning-conversations-updated', (_, updates) => cb(updates)); },
  onLeetCodeUpdated: (cb) => { ipcRenderer.removeAllListeners('leetcode-updated'); ipcRenderer.on('leetcode-updated', (_, dashboard) => cb(dashboard)); },
  onLeetCodeJudgeProgress: (cb) => { ipcRenderer.removeAllListeners('leetcode-judge-progress'); ipcRenderer.on('leetcode-judge-progress', (_, requestId, progress) => cb(requestId, progress)); },

  getDisplayProfile: () => ipcRenderer.invoke('get-display-profile'),
  getClipboard: () => ipcRenderer.invoke('get-clipboard'),
  setClipboard: (text) => ipcRenderer.invoke('set-clipboard', text),
  loadConversations: () => ipcRenderer.invoke('load-conversations'),
  saveConversation: (id, data) => ipcRenderer.invoke('save-conversation', id, data),
  deleteConversation: (id) => ipcRenderer.invoke('delete-conversation', id),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getAlwaysOnTop: () => ipcRenderer.invoke('get-always-on-top'),
  getWindowLayerState: () => ipcRenderer.invoke('get-window-layer-state'),
  setAlwaysOnTop: (value) => ipcRenderer.invoke('set-always-on-top', value),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  patchSettings: (patch) => ipcRenderer.invoke('patch-settings', patch),
  listModels: (settings) => ipcRenderer.invoke('list-models', settings),
  classifyBilibiliVideoEligibility: (payload) => ipcRenderer.invoke('classify-bilibili-video-eligibility', payload),
  identifyBilibiliQuery: (sourceText) => ipcRenderer.invoke('identify-bilibili-query', sourceText),
  searchBilibiliVideo: (query) => ipcRenderer.invoke('search-bilibili-video', query),
  searchBilibiliVideoAi: (requestId, query) => ipcRenderer.invoke('search-bilibili-video-ai', requestId, query),
  cancelBilibiliVideoSearch: (requestId) => ipcRenderer.send('cancel-bilibili-video-search', requestId),
  loadVideoHistory: () => ipcRenderer.invoke('load-video-history'),
  recordVideoHistory: (entry) => ipcRenderer.invoke('record-video-history', entry),
  removeVideoHistory: (bvid) => ipcRenderer.invoke('remove-video-history', bvid),
  clearVideoHistory: () => ipcRenderer.invoke('clear-video-history'),
  getVideoCacheStats: () => ipcRenderer.invoke('get-video-cache-stats'),
  clearVideoCache: () => ipcRenderer.invoke('clear-video-cache'),
  getBilibiliAuthState: () => ipcRenderer.invoke('get-bilibili-auth-state'),
  getBilibiliPlayback: (bvid) => ipcRenderer.invoke('get-bilibili-playback', bvid),
  enrichBilibiliStats: (bvids) => ipcRenderer.invoke('enrich-bilibili-stats', bvids),
  beginBilibiliLogin: () => ipcRenderer.invoke('begin-bilibili-login'),
  pollBilibiliLogin: (id) => ipcRenderer.invoke('poll-bilibili-login', id),
  logoutBilibili: () => ipcRenderer.invoke('logout-bilibili'),
  summarizeConversation: (id, messages) => ipcRenderer.invoke('summarize-conversation', id, messages),
  cancelSummary: (id) => ipcRenderer.send('cancel-summary', id),
  queueLearningAnalysis: (id, messages) => ipcRenderer.send('queue-learning-analysis', id, messages),
  flushLearningAnalysis: () => ipcRenderer.invoke('flush-learning-analysis'),
  getLearningDashboard: () => ipcRenderer.invoke('get-learning-dashboard'),
  generateLearningTemplate: (topicPath) => ipcRenderer.invoke('generate-learning-template', topicPath),
  deleteLearningTemplate: (topicPath) => ipcRenderer.invoke('delete-learning-template', topicPath),
  prepareLearningPackage: (itemId, requestedType, force = false) => ipcRenderer.invoke('prepare-learning-package', itemId, requestedType, force),
  judgeLearningAttempt: (itemId, answer) => ipcRenderer.invoke('judge-learning-attempt', itemId, answer),
  validateLearningCode: (language, code) => ipcRenderer.invoke('validate-learning-code', language, code),
  formatLearningCode: (language, code, cursorOffset) => ipcRenderer.invoke('format-learning-code', language, code, cursorOffset),
  patchLearningItem: (itemId, patch, options) => ipcRenderer.invoke('patch-learning-item', itemId, patch, options),
  deleteLearningItem: (itemId, options) => ipcRenderer.invoke('delete-learning-item', itemId, options),
  restoreLearningItem: (itemId) => ipcRenderer.invoke('restore-learning-item', itemId),
  purgeLearningItem: (itemId) => ipcRenderer.invoke('purge-learning-item', itemId),
  purgeAllLearningItems: () => ipcRenderer.invoke('purge-all-learning-items'),
  reviewLearningItem: (itemId, rating) => ipcRenderer.invoke('review-learning-item', itemId, rating),
  updateLearningSettings: (patch) => ipcRenderer.invoke('update-learning-settings', patch),
  getLeetCodeDashboard: () => ipcRenderer.invoke('get-leetcode-dashboard'),
  openLeetCodeLogin: () => ipcRenderer.invoke('open-leetcode-login'),
  logoutLeetCode: () => ipcRenderer.invoke('logout-leetcode'),
  importLeetCodePlan: (input) => ipcRenderer.invoke('import-leetcode-plan', input),
  selectLeetCodePlan: (slug) => ipcRenderer.invoke('select-leetcode-plan', slug),
  syncLeetCode: () => ipcRenderer.invoke('sync-leetcode'),
  getLeetCodeQuestionHistory: (slug) => ipcRenderer.invoke('get-leetcode-question-history', slug),
  getLeetCodeSubmissionDetail: (submissionId) => ipcRenderer.invoke('get-leetcode-submission-detail', submissionId),
  getLeetCodeWorkspace: (slug) => ipcRenderer.invoke('get-leetcode-workspace', slug),
  getLeetCodeSolutions: (questionSlug) => ipcRenderer.invoke('get-leetcode-solutions', questionSlug),
  getLeetCodeSolution: (solutionSlug) => ipcRenderer.invoke('get-leetcode-solution', solutionSlug),
  getLeetCodeVideoInfo: (uuid) => ipcRenderer.invoke('get-leetcode-video-info', uuid),
  getRemoteCodeCompletions: (payload) => ipcRenderer.invoke('get-remote-code-completions', payload),
  runLeetCodeCode: (payload) => ipcRenderer.invoke('run-leetcode-code', payload),
  submitLeetCodeCode: (payload) => ipcRenderer.invoke('submit-leetcode-code', payload),
  analyzeLeetCodeAttempt: (payload) => ipcRenderer.invoke('analyze-leetcode-attempt', payload),
  analyzeLeetCodeSubmission: (submissionId) => ipcRenderer.invoke('analyze-leetcode-submission', submissionId),
  openLeetCodeProblem: (slug) => ipcRenderer.invoke('open-leetcode-problem', slug),
  openProviderLink: (linkId) => ipcRenderer.invoke('open-provider-link', linkId),

  hideWindow: () => ipcRenderer.send('hide-window'),
  minimizeWindow: () => ipcRenderer.send('minimize-window'),
  setNativeLearningNavigation: (action) => ipcRenderer.send('set-native-learning-navigation', action),
  toggleFullscreen: () => ipcRenderer.send('toggle-fullscreen'),
  quitApp: () => ipcRenderer.send('quit-app')
});
